Repository FlintMC/FlintMC, pull requests merged in 2020-12, with the labels that each got.

#67 Add RegisteredSetting.getType
  mcapi/src/internal/java/net/flintmc/mcapi/internal/settings/flint/registered/DefaultRegisteredSetting.java
  mcapi/src/main/java/net/flintmc/mcapi/settings/flint/registered/RegisteredSetting.java
Labels: needs review

#57 Add FieldIdentifier and fix wrong obfuscation of annotated methods
  annotation-processing/autoload/src/main/java/net/flintmc/processing/autoload/AnnotationMeta.java
  annotation-processing/autoload/src/main/java/net/flintmc/processing/autoload/DetectableAnnotationProcessor.java
  annotation-processing/autoload/src/main/java/net/flintmc/processing/autoload/identifier/ClassIdentifier.java
  annotation-processing/autoload/src/main/java/net/flintmc/processing/autoload/identifier/ConstructorIdentifier.java
  annotation-processing/autoload/src/main/java/net/flintmc/processing/autoload/identifier/FieldIdentifier.java
  annotation-processing/autoload/src/main/java/net/flintmc/processing/autoload/identifier/MethodIdentifier.java
  framework/packages/src/internal/java/net/flintmc/framework/packages/internal/DefaultPackage.java
  render/gui/build.gradle.kts
  render/gui/src/main/java/net/flintmc/render/gui/windowing/MinecraftWindow.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/windowing/MinecraftFpsShadow.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/windowing/VersionedMinecraftWindow.java
  transform/launcher-plugin/src/main/java/net/flintmc/transform/launchplugin/FlintFrameworkInitializer.java
Labels: needs review

#69 Better error message when an invalid Subscribe annotation has been found
  framework/eventbus/src/internal/java/net/flintmc/framework/eventbus/internal/EventBusService.java
Labels: needs review

#75 Fix CI caching
  .github/workflows/gradle_build.yml
  .github/workflows/gradle_publish.yml
  gradlew
Labels: needs review

#79 Better error handling in the EventBus
  framework/eventbus/src/internal/java/net/flintmc/framework/eventbus/internal/DefaultEventBus.java
  framework/eventbus/src/internal/java/net/flintmc/framework/eventbus/internal/SubscribeService.java
  framework/eventbus/src/internal/java/net/flintmc/framework/eventbus/internal/method/subscribable/SubscribableService.java
  framework/eventbus/src/main/java/net/flintmc/framework/eventbus/EventBus.java
  framework/eventbus/src/main/java/net/flintmc/framework/eventbus/event/Event.java
  framework/eventbus/src/main/java/net/flintmc/framework/eventbus/event/EventDetails.java
  framework/eventbus/src/main/java/net/flintmc/framework/eventbus/event/subscribe/Subscribable.java
  framework/eventbus/src/main/java/net/flintmc/framework/eventbus/event/subscribe/Subscribe.java
Labels: improvement, needs review

#83 Add function to render the mouse without any screen and fix VersionedGuiInterceptor
  launcher/src/main/java/net/flintmc/launcher/classloading/RootClassLoader.java
  render/gui/src/main/java/net/flintmc/render/gui/event/ScreenRenderEvent.java
  render/gui/src/main/java/net/flintmc/render/gui/screen/BuiltinScreenDisplayer.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/VersionedGuiInterceptor.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/event/VersionedScreenRenderEventInjector.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/screen/VersionedBuiltinScreenDisplayer.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/screen/VersionedDummyScreen.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/screen/VersionedScreenNameMapper.java
  transform/minecraft/src/internal/java/net/flintmc/transform/minecraft/internal/PreMinecraftTransformerService.java
Labels: improvement, needs review

#84 Add method to check whether a screen is opened
  render/gui/src/main/java/net/flintmc/render/gui/screen/BuiltinScreenDisplayer.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/screen/VersionedBuiltinScreenDisplayer.java
Labels: feature, needs review

#85 Fix wrongly fired ScreenNameChangedEvent
  render/gui/src/main/java/net/flintmc/render/gui/screen/BuiltinScreenDisplayer.java
  render/gui/src/main/java/net/flintmc/render/gui/screen/ScreenName.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/VersionedGuiInterceptor.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/screen/VersionedBuiltinScreenDisplayer.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/screen/VersionedScreenNameMapper.java
Labels: bug
