Repository FlintMC/FlintMC, pull requests merged in 2021-03, with the labels that each got.

#145 Add some standalone features
  framework/config/src/internal/java/net/flintmc/framework/config/internal/generator/DefaultConfigGenerator.java
  framework/config/src/internal/java/net/flintmc/framework/config/internal/generator/DefaultGeneratingConfig.java
  framework/config/src/internal/java/net/flintmc/framework/config/internal/generator/base/DefaultConfigImplementer.java
  framework/config/src/internal/java/net/flintmc/framework/config/internal/generator/service/ConfigGenerationService.java
  framework/config/src/internal/java/net/flintmc/framework/config/internal/generator/service/ConfigImplementationMapper.java
  framework/config/src/internal/java/net/flintmc/framework/config/internal/serialization/DefaultConfigSerializationService.java
  framework/config/src/main/java/net/flintmc/framework/config/annotation/Config.java
  framework/config/src/main/java/net/flintmc/framework/config/generator/GeneratingConfig.java
  framework/config/src/main/java/net/flintmc/framework/config/generator/ParsedConfig.java
  framework/inject/src/internal/java/net/flintmc/framework/inject/internal/method/MethodInjectorFactory.java
  framework/packages/src/internal/java/net/flintmc/framework/packages/internal/DefaultPackageLoader.java
  framework/packages/src/internal/java/net/flintmc/framework/packages/internal/load/DefaultPackageFinder.java
  launcher/src/main/java/net/flintmc/launcher/LaunchArguments.java
  launcher/src/main/java/net/flintmc/launcher/LaunchController.java
  transform/javassist/src/internal/java/net/flintmc/transform/javassist/internal/DefaultClassTransformService.java
  transform/launcher-plugin/src/main/java/net/flintmc/transform/launchplugin/FlintLauncherPlugin.java
  util/mapping/src/main/java/net/flintmc/util/mappings/ClassMappingProvider.java
Labels: feature, needs review

#150 Improve categories
  gradle/wrapper/gradle-wrapper.properties
  mcapi/src/internal/java/net/flintmc/mcapi/internal/settings/flint/registered/DefaultSettingsProvider.java
  mcapi/src/internal/java/net/flintmc/mcapi/internal/settings/flint/serializer/DefaultJsonSettingsSerializer.java
  mcapi/src/main/java/net/flintmc/mcapi/settings/flint/annotation/ui/CategoryGroup.java
  mcapi/src/main/java/net/flintmc/mcapi/settings/flint/registered/SettingsProvider.java
  mcapi/src/main/java/net/flintmc/mcapi/settings/flint/serializer/JsonSettingsSerializer.java
  mcapi/src/main/java/net/flintmc/mcapi/settings/game/MinecraftConfiguration.java
Labels: improvement

#156 Fix wrong priority of ConfigStorageService, add eventClass to EventDetails
  framework/config/src/internal/java/net/flintmc/framework/config/internal/storage/ConfigStorageService.java
  framework/config/src/internal/java/net/flintmc/framework/config/internal/storage/DefaultConfigStorageProvider.java
  framework/eventbus/src/internal/java/net/flintmc/framework/eventbus/internal/DefaultEventBus.java
  framework/eventbus/src/internal/java/net/flintmc/framework/eventbus/internal/method/subscribable/EventTransform.java
  framework/eventbus/src/internal/java/net/flintmc/framework/eventbus/internal/method/subscribable/SubscribableService.java
  framework/eventbus/src/main/java/net/flintmc/framework/eventbus/EventBus.java
  framework/eventbus/src/main/java/net/flintmc/framework/eventbus/event/EventDetails.java
Labels: bug, needs review

#163 Fix initialization of the keybind setting handler
  mcapi/src/internal/java/net/flintmc/mcapi/internal/settings/game/keybind/KeyBindSettingHandler.java
  mcapi/src/main/java/net/flintmc/mcapi/settings/game/configuration/KeyBindingConfiguration.java
  mcapi/src/main/java/net/flintmc/mcapi/settings/game/keybind/KeyBinding.java
  mcapi/src/main/java/net/flintmc/mcapi/settings/game/keybind/KeyBindingList.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/render/geometric/VersionedRectangleRenderer.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/settings/game/configuration/VersionedKeyBindingConfiguration.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/settings/game/keybind/VersionedKeyBinding.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/settings/game/keybind/VersionedKeybindingList.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/render/geometric/VersionedRectangleRenderer.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/settings/game/configuration/VersionedKeyBindingConfiguration.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/settings/game/keybind/VersionedKeyBinding.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/settings/game/keybind/VersionedKeyBindingList.java
Labels: bug, needs review
