Repository FlintMC/FlintMC, pull requests merged in 2021-02, with the labels that each got.

#128 Fix some more obfuscation errors in 1.16.5
  mcapi/src/internal/java/net/flintmc/mcapi/internal/server/status/DefaultServerStatusResolver.java
  mcapi/src/main/java/net/flintmc/mcapi/server/status/ServerStatusResolver.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/server/VersionedServerAddress.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/ChatEventInjector.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/entity/event/VersionedEntityRenderNameEventInjectorTransformer.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/items/mapper/VersionedMinecraftItemMapper.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/server/VersionedServerAddress.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/server/event/VersionedServerListUpdateEventInjector.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/server/payload/CustomPayloadInterceptor.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/world/event/VersionedWorldLoadEventInjector.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/VersionedGuiInterceptor.java
  render/gui/src/v1_16_5/java/net/flintmc/render/gui/v1_16_5/VersionedGuiInterceptor.java
Labels: bug, needs review

#131 Update the gradle property for mojang login in readme
  README.md
Labels: bug

#135 Fix NPE in the NetworkPlayerInfo when not connected to a server
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/player/network/VersionedNetworkPlayerInfo.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/player/network/VersionedNetworkPlayerInfo.java
Labels: bug, needs review

#136 World stats api
  mcapi/build.gradle.kts
  mcapi/src/internal/java/net/flintmc/mcapi/internal/world/stats/DefaultItemWorldStat.java
  mcapi/src/main/java/net/flintmc/mcapi/entity/type/EntityType.java
  mcapi/src/main/java/net/flintmc/mcapi/entity/type/EntityTypeBuilder.java
  mcapi/src/main/java/net/flintmc/mcapi/items/inventory/event/InventoryUpdateSlotEvent.java
  mcapi/src/main/java/net/flintmc/mcapi/items/mapper/MinecraftItemMapper.java
  mcapi/src/main/java/net/flintmc/mcapi/server/event/PacketEvent.java
  mcapi/src/main/java/net/flintmc/mcapi/world/stats/StatsCategory.java
  mcapi/src/main/java/net/flintmc/mcapi/world/stats/WorldStatType.java
  mcapi/src/main/java/net/flintmc/mcapi/world/stats/WorldStats.java
  mcapi/src/main/java/net/flintmc/mcapi/world/stats/WorldStatsProvider.java
  mcapi/src/main/java/net/flintmc/mcapi/world/stats/event/PlayerStatsUpdateEvent.java
  mcapi/src/main/java/net/flintmc/mcapi/world/stats/value/GeneralWorldStat.java
  mcapi/src/main/java/net/flintmc/mcapi/world/stats/value/ItemWorldStat.java
  mcapi/src/main/java/net/flintmc/mcapi/world/stats/value/MobWorldStat.java
  mcapi/src/main/java/net/flintmc/mcapi/world/stats/value/WorldStat.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/entity/type/VersionedEntityType.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/entity/type/VersionedEntityTypeBuilder.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/entity/type/VersionedEntityTypeMapper.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/items/mapper/VersionedMinecraftItemMapper.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/server/event/PacketEventInjectionTransformer.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/server/event/PacketEventInjector.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/server/event/ServerConnectEventInjector.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/world/stats/StatsScreenShadow.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/world/stats/VersionedWorldStatsMapper.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/world/stats/VersionedWorldStatsProvider.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/world/stats/event/DefaultPlayerStatsUpdateEvent.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/entity/type/VersionedEntityType.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/entity/type/VersionedEntityTypeBuilder.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/entity/type/VersionedEntityTypeMapper.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/items/mapper/VersionedMinecraftItemMapper.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/server/event/PacketEventInjectionTransformer.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/server/event/PacketEventInjector.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/server/event/ServerConnectEventInjector.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/world/stats/StatsScreenShadow.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/world/stats/VersionedWorldStatsMapper.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/world/stats/VersionedWorldStatsProvider.java
Labels: feature, needs review

#138 Fix parsing of legacy text components in 1.16.5
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/VersionedMinecraftComponentMapper.java
Labels: bug, needs review

#139 Fix errors in the obfuscated environment
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/world/stats/VersionedWorldStatsInterrupter.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/world/stats/VersionedWorldStatsProvider.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/world/stats/VersionedWorldStatsInterrupter.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/world/stats/VersionedWorldStatsProvider.java
  minecraft/minecraft-1-16-5/version.json
Labels: bug

#142 Fix that config methods from super classes are generated in the wrong implementation
  framework/config/src/internal/java/net/flintmc/framework/config/internal/generator/method/DefaultConfigMethodResolver.java
Labels: bug, needs review

#146 Fix newValue in the pre phase of the ConfigValueUpdateEvent
  framework/config/src/internal/java/net/flintmc/framework/config/internal/generator/method/ConfigMethodGenerationUtils.java
Labels: bug, needs review
