Repository FlintMC/FlintMC, pull requests merged in 2021-05, with the labels that each got.

#183 Extract launcher/versions into an extra repository
  .github/workflows/gradle_publish.yml
  bootstrap/build.gradle.kts
  bootstrap/src/main/java/net/flintmc/bootstrap/Bootstrap.java
  framework/config/src/internal/java/net/flintmc/framework/config/internal/transform/DefaultConfigTransformer.java
  framework/eventbus/src/internal/java/net/flintmc/framework/eventbus/internal/method/subscribable/SubscribableService.java
  framework/packages/build.gradle.kts
  framework/packages/src/internal/java/net/flintmc/framework/packages/internal/DefaultPackageManifestLoader.java
  framework/packages/src/internal/java/net/flintmc/framework/packages/internal/load/DefaultDependencyGraphBuilder.java
  framework/stereotype/build.gradle.kts
  launcher/src/main/java/net/flintmc/launcher/FlintLauncher.java
  launcher/src/main/java/net/flintmc/launcher/LaunchArguments.java
  launcher/src/main/java/net/flintmc/launcher/LaunchController.java
  launcher/src/main/java/net/flintmc/launcher/classloading/ChildClassLoader.java
  launcher/src/main/java/net/flintmc/launcher/classloading/CircularClassLoadException.java
  launcher/src/main/java/net/flintmc/launcher/classloading/RootClassLoader.java
  launcher/src/main/java/net/flintmc/launcher/classloading/common/ClassInformation.java
  launcher/src/main/java/net/flintmc/launcher/classloading/common/CommonClassLoader.java
  launcher/src/main/java/net/flintmc/launcher/classloading/common/CommonClassLoaderHelper.java
  launcher/src/main/java/net/flintmc/launcher/service/LauncherPlugin.java
  launcher/src/main/java/net/flintmc/launcher/service/PreLaunchException.java
  launcher/src/main/resources/sentry.properties
  mcapi/build.gradle.kts
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/ChatEventInjector.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/entity/render/ModelRendererInterceptor.java
  minecraft/minecraft-1-15-2/build.gradle.kts
  minecraft/minecraft-1-15-2/version.json
  minecraft/minecraft-1-16-5/build.gradle.kts
  minecraft/minecraft-1-16-5/version.json
  settings.gradle.kts
  transform/exceptions/build.gradle.kts
  transform/exceptions/src/main/java/net/flintmc/transform/exceptions/ClassTransformException.java
  transform/javassist/src/internal/java/net/flintmc/transform/javassist/internal/DefaultClassTransformService.java
  transform/javassist/src/internal/java/net/flintmc/transform/javassist/internal/DefaultConsumerBasedClassTransformMeta.java
  transform/javassist/src/internal/java/net/flintmc/transform/javassist/internal/DefaultMethodBasedClassTransformMeta.java
  transform/javassist/src/main/java/net/flintmc/transform/javassist/ClassTransformMeta.java
  transform/launcher-plugin/src/main/java/net/flintmc/transform/launchplugin/FlintLauncherPlugin.java
  transform/launcher-plugin/src/main/java/net/flintmc/transform/launchplugin/LateInjectedTransformer.java
  transform/launcher-plugin/src/main/resources/META-INF/services/net.flintmc.launcher.service.LauncherPlugin
  transform/minecraft-obfuscator/src/main/java/net/flintmc/transform/minecraft/obfuscate/MinecraftInstructionObfuscator.java
  transform/shadow/src/internal/java/net/flintmc/transform/shadow/internal/ShadowService.java
  transform/shadow/src/internal/java/net/flintmc/transform/shadow/internal/handler/ShadowHandler.java
  transform/shadow/src/internal/java/net/flintmc/transform/shadow/internal/handler/defaults/ShadowFieldCreateHandler.java
  transform/shadow/src/internal/java/net/flintmc/transform/shadow/internal/handler/defaults/ShadowGetterHandler.java
  transform/shadow/src/internal/java/net/flintmc/transform/shadow/internal/handler/defaults/ShadowProxyHandler.java
  transform/shadow/src/internal/java/net/flintmc/transform/shadow/internal/handler/defaults/ShadowSetterHandler.java
  util/mapping/build.gradle.kts
  util/mapping/src/main/java/net/flintmc/util/mappings/ClassMapping.java
  util/mapping/src/main/java/net/flintmc/util/mappings/ClassMappingProvider.java
  util/mapping/src/main/java/net/flintmc/util/mappings/DefaultMappingFileProvider.java
  util/mapping/src/main/java/net/flintmc/util/mappings/MappingFileProvider.java
  util/mapping/src/main/java/net/flintmc/util/mappings/MappingParser.java
  util/mapping/src/main/java/net/flintmc/util/mappings/MappingType.java
  util/mapping/src/main/java/net/flintmc/util/mappings/McpMappingIndexProvider.java
  util/mapping/src/main/java/net/flintmc/util/mappings/McpMappingParser.java
  util/mapping/src/main/java/net/flintmc/util/mappings/MethodMapping.java
Labels: feature, needs review

#186 Add ServerConnectProgressEvent
  mcapi/src/internal/java/net/flintmc/mcapi/internal/server/event/DefaultServerConnectProgressEvent.java
  mcapi/src/main/java/net/flintmc/mcapi/server/event/ServerConnectProgressEvent.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/server/event/ServerConnectProgressEventInjector.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/server/event/shadow/ClientLoginNetHandlerShadow.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/server/event/ServerConnectProgressEventInjector.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/server/event/shadow/ClientLoginNetHandlerShadow.java
Labels: feature, needs review

#185 Add methods to fire a key event to Minecraft
  render/gui/src/internal/java/net/flintmc/render/gui/internal/windowing/InternalWindow.java
  render/gui/src/main/java/net/flintmc/render/gui/windowing/MinecraftWindow.java
  render/gui/src/main/java/net/flintmc/render/gui/windowing/Window.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/VersionedInputInterceptor.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/glfw/VersionedGLFWCallbacks.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/glfw/VersionedGLFWInputConverter.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/windowing/VersionedMinecraftWindow.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/windowing/VersionedWindow.java
  render/gui/src/v1_16_5/java/net/flintmc/render/gui/v1_16_5/VersionedInputInterceptor.java
  render/gui/src/v1_16_5/java/net/flintmc/render/gui/v1_16_5/glfw/VersionedGLFWCallbacks.java
  render/gui/src/v1_16_5/java/net/flintmc/render/gui/v1_16_5/glfw/VersionedGLFWInputConverter.java
  render/gui/src/v1_16_5/java/net/flintmc/render/gui/v1_16_5/windowing/VersionedMinecraftWindow.java
  render/gui/src/v1_16_5/java/net/flintmc/render/gui/v1_16_5/windowing/VersionedWindow.java
Labels: feature, needs review

#192 Improve intrusive rendering
  render/gui/src/internal/java/net/flintmc/render/gui/internal/windowing/DefaultWindowManager.java
  render/gui/src/internal/java/net/flintmc/render/gui/internal/windowing/InternalWindow.java
  render/gui/src/main/java/net/flintmc/render/gui/screen/ScreenName.java
  render/gui/src/main/java/net/flintmc/render/gui/windowing/WindowRenderer.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/VersionedGuiInterceptor.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/screen/VersionedScreenNameMapper.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/windowing/VersionedMinecraftWindow.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/windowing/VersionedWindow.java
  render/gui/src/v1_16_5/java/net/flintmc/render/gui/v1_16_5/VersionedGuiInterceptor.java
  render/gui/src/v1_16_5/java/net/flintmc/render/gui/v1_16_5/screen/VersionedScreenNameMapper.java
  render/gui/src/v1_16_5/java/net/flintmc/render/gui/v1_16_5/windowing/VersionedMinecraftWindow.java
  render/gui/src/v1_16_5/java/net/flintmc/render/gui/v1_16_5/windowing/VersionedWindow.java
  render/webgui/src/internal/java/net/flintmc/render/gui/webgui/internal/MinecraftWebFileSystem.java
Labels: improvement

#193 Implement execution of chat ClickEvents
  mcapi/src/internal/java/net/flintmc/mcapi/internal/chat/component/DefaultChatComponent.java
  mcapi/src/internal/java/net/flintmc/mcapi/internal/chat/component/event/DefaultClickActionExecutorService.java
  mcapi/src/internal/java/net/flintmc/mcapi/internal/chat/component/event/DefaultClickEvent.java
  mcapi/src/internal/java/net/flintmc/mcapi/internal/chat/component/event/DefaultClickEventFactory.java
  mcapi/src/internal/java/net/flintmc/mcapi/internal/chat/serializer/gson/GsonChatComponentSerializer.java
  mcapi/src/main/java/net/flintmc/mcapi/chat/ChatController.java
  mcapi/src/main/java/net/flintmc/mcapi/chat/component/event/ClickActionExecutor.java
  mcapi/src/main/java/net/flintmc/mcapi/chat/component/event/ClickEvent.java
  mcapi/src/main/java/net/flintmc/mcapi/chat/component/event/ClickEventAction.java
  mcapi/src/main/java/net/flintmc/mcapi/chat/event/ChatInputChangeEvent.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/chat/ScreenTextShadow.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/chat/VersionedChatController.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/chat/VersionedMinecraftComponentMapper.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/chat/component/event/VersionedClipboardActionExecutor.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/chat/component/event/VersionedOpenFileActionExecutor.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/chat/component/event/VersionedOpenUrlActionExecutor.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/chat/component/event/VersionedRunCommandActionExecutor.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/chat/component/event/VersionedSuggestCommandActionExecutor.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/chat/event/ChatEventInjector.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/chat/event/ChatInputChangeEventInjector.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/ScreenTextShadow.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/VersionedChatController.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/VersionedMinecraftComponentMapper.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/component/event/VersionedClipboardActionExecutor.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/component/event/VersionedOpenFileActionExecutor.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/component/event/VersionedOpenUrlActionExecutor.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/component/event/VersionedRunCommandActionExecutor.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/component/event/VersionedSuggestCommandActionExecutor.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/event/ChatEventInjector.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/event/ChatInputChangeEventInjector.java
Labels: feature, needs review

#195 Fix Gui Interceptor
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/player/skin/SkinManagerShadow.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/player/skin/VersionedHeadSkinLoadingTask.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/player/skin/VersionedSkinLoadingTask.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/player/skin/VersionedSkinProvider.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/resources/SkinManagerShadow.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/resources/VersionedMinecraftSkinCacheDirectoryProvider.java
  render/gui/src/v1_15_2/java/net/flintmc/render/gui/v1_15_2/VersionedGuiInterceptor.java
  render/gui/src/v1_16_5/java/net/flintmc/render/gui/v1_16_5/VersionedGuiInterceptor.java
Labels: bug

#200 Remove class name in front of fields in the same class
  framework/inject/src/internal/java/net/flintmc/framework/inject/internal/method/DefaultMethodInjectionUtils.java
  transform/hook/src/internal/java/net/flintmc/transform/hook/internal/HookService.java
Labels: bug

#204 Fix modification of the ChatComponent insertion
  mcapi/src/internal/java/net/flintmc/mcapi/internal/chat/component/DefaultChatComponent.java
Labels: bug

#206 Add ChatLocation and senderId to ChatReceiveEvent
  mcapi/src/internal/java/net/flintmc/mcapi/internal/chat/event/DefaultChatReceiveEvent.java
  mcapi/src/main/java/net/flintmc/mcapi/chat/event/ChatReceiveEvent.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/chat/event/ChatEventInjector.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/chat/event/ChatEventInjectorTransformer.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/chat/event/ReceivedChatMessage.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/world/lan/VersionedLanWorldService.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/event/ChatEventInjector.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/event/ChatEventInjectorTransformer.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/chat/event/ReceivedChatMessage.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/world/lan/VersionedLanWorldService.java
Labels: feature

#208 Move DNS resolving to ServerData.getServerAddress
  mcapi/src/internal/java/net/flintmc/mcapi/internal/server/DefaultServerData.java
  mcapi/src/main/java/net/flintmc/mcapi/server/ServerData.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/server/VersionedServerAddress.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/server/VersionedServerList.java
  mcapi/src/v1_15_2/java/net/flintmc/mcapi/v1_15_2/server/event/ModServerList.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/server/VersionedServerAddress.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/server/VersionedServerList.java
  mcapi/src/v1_16_5/java/net/flintmc/mcapi/v1_16_5/server/event/ModServerList.java
Labels: improvement, needs review
